### ISSUE TITLE
Youtube Bar Issue

### ISSUE THREAD

**Issue by sasecai** [HasanNaser/hide-youtube-recommendations#1]
![image](https://user-images.githubusercontent.com/63098900/104819371-b64de000-5835-11eb-8c1d-6dfe9706647c.png)

Half of the youtube bar is hidden and the mic icon is under it in opera.

![image](https://user-images.githubusercontent.com/63098900/104819356-95858a80-5835-11eb-870f-8b1681556577.png)

**Comment by HasanNaser** [comment]
Hi @sasecai  
I think it is  becouse youtube last updates :(
thank you for report that, I will fix it

**Comment by HasanNaser** [comment]
Hi @sasecai 
The problem has been fixed. You can download the package again and use it
